
CXXFLAGS=-std=c++11 -O3 -fopenmp -march=native -mtune=native
LDFLAGS=-fopenmp 
CUDAFLAGS=-O3 -arch=sm_37 -std=c++11

polynomial:

polynomial_gpu:
	nvcc $(CUDAFLAGS) polynomial_gpu.cu -o polynomial_gpu

bench_cpu:
	./queue_cpu.sh

bench_gpu:
	./queue_gpu.sh

clean:
	-rm polynomial polynomial_gpu
